# Data Exploration

This notebook explores data prior to the 2015 tree census

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gp

%matplotlib inline
plt.style.use('fivethirtyeight')

In [2]:
#Data reading
trees95 = pd.read_csv('../data/1995_Street_Tree_Census.csv')

/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
trees95.head()

,RecordId,Address,House_Number,Street,Zip_Original,CB_Original,Site,Species,Diameter,Condition,...,Latitude,CB_New,Zip_New,CensusTract_2010,CensusBlock_2010,NTA_2010,SegmentID,Spc_Common,Spc_Latin,Location
0,1,245 E 17 ST,245,E 17 ST,10003,106,Front,PLAC,8,Unknown,...,40.734551,106,10003,48,2000,MN21,33134,LONDON PLANETREE,PLATANUS ACERIFOLIA,"(40.734551, -73.984235)"
1,2,80 N MOORE ST,80,N MOORE ST,10013,101,Side,ACPL,7,Good,...,40.720159,101,10013,39,2001,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)"
2,3,80 N MOORE ST,80,N MOORE ST,10013,101,Side,ACPL,6,Good,...,40.720159,101,10013,39,2001,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)"
3,4,80 N MOORE ST,80,N MOORE ST,10013,101,Side,ACPL,7,Excellent,...,40.720159,101,10013,39,2001,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)"
4,5,80 N MOORE ST,80,N MOORE ST,10013,101,Side,ACPL,6,Good,...,40.720159,101,10013,39,2001,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)"